import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Card,
  Button,
  Input,
  Badge,
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
  useToast,
} from '../common';
import { INITIAL_PRODUCTS, INITIAL_WAREHOUSES } from '../../mock/mockData';
import {
  ArrowLeft,
  Printer,
  Ban,
  CheckCircle2,
  Plus,
  Trash2,
  AlertTriangle,
  Building,
  MapPin,
  Calendar,
  User,
  Check,
} from 'lucide-react';

export default function DocumentDetailView({
  document: initialDoc,
  docType = 'receipt', // 'receipt' | 'delivery'
  onBack,
  onSaveDocument,
}) {
  const isReceipt = docType === 'receipt';
  const { addToast } = useToast();

  const steps = isReceipt
    ? ['Draft', 'Ready', 'Done']
    : ['Draft', 'Waiting', 'Ready', 'Done'];

  const defaultWarehouse = 'WH';
  const defaultOp = isReceipt ? 'IN' : 'OUT';
  const autoGeneratedRef = `${defaultWarehouse}/${defaultOp}/${String(Math.floor(Math.random() * 9000) + 1000)}`;

  const [doc, setDoc] = useState(
    initialDoc || {
      id: `doc-${Date.now()}`,
      reference: autoGeneratedRef,
      partner: isReceipt ? 'Nike Global Sourcing Ltd.' : 'Downtown Flagship Store',
      contact: isReceipt ? '' : 'Downtown Flagship Store',
      deliveryAddress: isReceipt ? '' : '529 Broadway, New York, NY 10012',
      warehouse: defaultWarehouse,
      responsible: 'Alex Vance',
      scheduleDate: new Date().toISOString().split('T')[0],
      status: 'Draft',
      note: '',
      lines: [
        {
          id: `line-1`,
          productId: INITIAL_PRODUCTS[0].id,
          name: INITIAL_PRODUCTS[0].name,
          sku: INITIAL_PRODUCTS[0].sku,
          expectedQty: 100,
          qty: 100,
          doneQty: 0,
          availableQty: INITIAL_PRODUCTS[0].freeToUse,
          uom: INITIAL_PRODUCTS[0].uom,
        },
      ],
    }
  );

  const [isAddingLine, setIsAddingLine] = useState(false);
  const [selectedProductId, setSelectedProductId] = useState(INITIAL_PRODUCTS[0].id);
  const [newLineQty, setNewLineQty] = useState(50);

  const currentStepIdx = steps.indexOf(doc.status);

  // Stepper Transitions
  const handleNextStep = () => {
    if (isReceipt) {
      if (doc.status === 'Draft') {
        const updated = { ...doc, status: 'Ready' };
        setDoc(updated);
        if (onSaveDocument) onSaveDocument(updated);
        addToast({
          title: 'Marked as Ready',
          description: `Receipt ${doc.reference} staged for dock receiving validation.`,
          variant: 'accent',
        });
      } else if (doc.status === 'Ready') {
        const updated = {
          ...doc,
          status: 'Done',
          lines: doc.lines.map((l) => ({ ...l, doneQty: l.expectedQty || l.qty })),
        };
        setDoc(updated);
        if (onSaveDocument) onSaveDocument(updated);
        addToast({
          title: 'Receipt Validated',
          description: `Voucher ${doc.reference} locked. Stock quantities committed to ledger.`,
          variant: 'success',
        });
      }
    } else {
      // Delivery Stepper
      if (doc.status === 'Draft') {
        const anyShortfall = doc.lines.some((l) => l.availableQty < l.qty);
        const nextStatus = anyShortfall ? 'Waiting' : 'Ready';
        const updated = { ...doc, status: nextStatus };
        setDoc(updated);
        if (onSaveDocument) onSaveDocument(updated);

        if (anyShortfall) {
          addToast({
            title: 'Stock Allocation Shortfall',
            description: `Delivery ${doc.reference} placed in Waiting state due to insufficient on-hand inventory.`,
            variant: 'danger',
          });
        } else {
          addToast({
            title: 'Inventory Reserved',
            description: `Stock verified and reserved for ${doc.reference}. Staged for dispatch.`,
            variant: 'accent',
          });
        }
      } else if (doc.status === 'Waiting') {
        const updated = { ...doc, status: 'Ready' };
        setDoc(updated);
        if (onSaveDocument) onSaveDocument(updated);
        addToast({
          title: 'Re-Checked & Staged',
          description: `Delivery order ${doc.reference} moved to Ready.`,
          variant: 'accent',
        });
      } else if (doc.status === 'Ready') {
        const updated = { ...doc, status: 'Done' };
        setDoc(updated);
        if (onSaveDocument) onSaveDocument(updated);
        addToast({
          title: 'Dispatch Validated',
          description: `Delivery order ${doc.reference} completed and signed out.`,
          variant: 'success',
        });
      }
    }
  };

  const handleCancelDocument = () => {
    if (window.confirm('Are you sure you want to cancel this operation document?')) {
      const updated = { ...doc, status: 'Canceled' };
      setDoc(updated);
      if (onSaveDocument) onSaveDocument(updated);
      addToast({
        title: 'Document Canceled',
        description: `Operation ${doc.reference} marked as Canceled.`,
        variant: 'warning',
      });
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCreateNew = () => {
    const newRef = `${doc.warehouse}/${defaultOp}/${String(Math.floor(Math.random() * 9000) + 1000)}`;
    const fresh = {
      id: `doc-${Date.now()}`,
      reference: newRef,
      partner: '',
      contact: '',
      deliveryAddress: '',
      warehouse: doc.warehouse,
      responsible: 'Alex Vance',
      scheduleDate: new Date().toISOString().split('T')[0],
      status: 'Draft',
      note: '',
      lines: [],
    };
    setDoc(fresh);
    addToast({
      title: 'New Voucher Drafted',
      description: `Draft created with reference ${newRef}.`,
      variant: 'info',
    });
  };

  const handleAddProductLine = (e) => {
    e.preventDefault();
    const product = INITIAL_PRODUCTS.find((p) => p.id === selectedProductId) || INITIAL_PRODUCTS[0];
    const qty = parseInt(newLineQty, 10) || 1;

    const newLine = {
      id: `line-${Date.now()}`,
      productId: product.id,
      name: product.name,
      sku: product.sku,
      expectedQty: qty,
      qty: qty,
      doneQty: 0,
      availableQty: product.freeToUse,
      uom: product.uom,
    };

    const updated = { ...doc, lines: [...doc.lines, newLine] };
    setDoc(updated);
    if (onSaveDocument) onSaveDocument(updated);
    setIsAddingLine(false);

    addToast({
      title: 'Line Item Added',
      description: `${product.name} (${qty} ${product.uom}) appended to document.`,
      variant: 'info',
    });
  };

  const handleRemoveLine = (lineId) => {
    const removedLine = doc.lines.find((l) => l.id === lineId);
    const updated = { ...doc, lines: doc.lines.filter((l) => l.id !== lineId) };
    setDoc(updated);
    if (onSaveDocument) onSaveDocument(updated);
    if (removedLine) {
      addToast({
        title: 'Line Item Removed',
        description: `${removedLine.name} removed from document.`,
        variant: 'warning',
      });
    }
  };

  const linesWithShortfall = !isReceipt
    ? doc.lines.filter((l) => (l.availableQty !== undefined ? l.availableQty < l.qty : false))
    : [];

  const isPrintEnabled = doc.status === 'Done';

  return (
    <div className="space-y-6">
      {/* 1. TOP ACTION BAR */}
      <section className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl bg-surface/90 border border-white/[0.08] backdrop-blur-xl">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={onBack}
            leftIcon={<ArrowLeft className="w-4 h-4" />}
          >
            Back to List
          </Button>

          <div className="h-5 w-px bg-white/[0.1] hidden sm:block" />

          {/* Action buttons: New / Cancel / Print */}
          <div className="flex items-center gap-2">
            <Button variant="secondary" size="sm" onClick={handleCreateNew}>
              New
            </Button>

            <Button
              variant="destructive"
              size="sm"
              disabled={doc.status === 'Done' || doc.status === 'Canceled'}
              onClick={handleCancelDocument}
              leftIcon={<Ban className="w-3.5 h-3.5" />}
            >
              Cancel
            </Button>

            {/* Print button: Enabled ONLY once status = 'Done' */}
            <Button
              variant="outline"
              size="sm"
              disabled={!isPrintEnabled}
              onClick={handlePrint}
              leftIcon={<Printer className="w-3.5 h-3.5" />}
              title={!isPrintEnabled ? 'Print enabled once status is Done' : 'Print Slip'}
            >
              Print
            </Button>
          </div>
        </div>

        {/* Stepper Progression Button */}
        <div className="flex items-center gap-3">
          {doc.status !== 'Done' && doc.status !== 'Canceled' && (
            <Button
              variant="primary"
              size="sm"
              onClick={handleNextStep}
              rightIcon={<CheckCircle2 className="w-4 h-4" />}
            >
              {isReceipt
                ? doc.status === 'Draft'
                  ? 'Mark as Todo'
                  : 'Validate Receipt'
                : doc.status === 'Draft'
                ? 'Check Availability'
                : doc.status === 'Waiting'
                ? 'Re-check Stock'
                : 'Validate Delivery'}
            </Button>
          )}

          {doc.status === 'Done' && (
            <Badge variant="done" size="md" dot>
              Validated & Locked
            </Badge>
          )}
        </div>
      </section>

      {/* 2. ANIMATED STATUS STEPPER BAR (Framer Motion) */}
      <section className="p-4 rounded-2xl bg-surface/75 border border-white/[0.08] backdrop-blur-xl">
        <div className="flex items-center justify-between max-w-2xl mx-auto px-2 relative">
          {steps.map((step, idx) => {
            const isCompleted = currentStepIdx > idx;
            const isCurrent = doc.status.toLowerCase() === step.toLowerCase();

            return (
              <React.Fragment key={step}>
                <div className="flex flex-col items-center gap-1.5 relative z-10">
                  <motion.div
                    animate={{
                      scale: isCurrent ? 1.15 : 1,
                      backgroundColor: isCurrent
                        ? '#FF5500'
                        : isCompleted
                        ? 'rgba(16, 185, 129, 0.2)'
                        : 'rgba(255, 255, 255, 0.05)',
                    }}
                    transition={{ type: 'spring', stiffness: 350, damping: 25 }}
                    className={`w-8 h-8 rounded-full flex items-center justify-center font-mono text-xs font-bold ${
                      isCurrent
                        ? 'text-white shadow-accent-glow'
                        : isCompleted
                        ? 'text-emerald-400 border border-status-success/40'
                        : 'text-neutral-400 border border-white/[0.08]'
                    }`}
                  >
                    {isCompleted ? <Check className="w-4 h-4" /> : idx + 1}
                  </motion.div>
                  <span
                    className={`text-xs font-display font-semibold uppercase tracking-wider ${
                      isCurrent
                        ? 'text-accent font-bold'
                        : isCompleted
                        ? 'text-emerald-400'
                        : 'text-neutral-400'
                    }`}
                  >
                    {step}
                  </span>
                </div>

                {idx < steps.length - 1 && (
                  <div className="flex-1 h-0.5 mx-3 bg-white/[0.08] relative overflow-hidden">
                    <motion.div
                      initial={false}
                      animate={{
                        width: currentStepIdx > idx ? '100%' : '0%',
                      }}
                      transition={{ duration: 0.35, ease: 'easeOut' }}
                      className="absolute inset-0 bg-emerald-400/60"
                    />
                  </div>
                )}
              </React.Fragment>
            );
          })}
        </div>
      </section>

      {/* 3. DOCUMENT HEADER CARD */}
      <Card className="p-6 sm:p-8 space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/[0.08] pb-6">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="font-mono text-[10px] uppercase font-bold text-accent tracking-widest">
                {isReceipt ? 'INBOUND RECEIPT VOUCHER' : 'OUTBOUND DELIVERY NOTE'}
              </span>
            </div>
            <h2 className="font-display font-black text-3xl sm:text-4xl text-white tracking-tight uppercase">
              {doc.reference}
            </h2>
          </div>

          <div className="flex items-center gap-3">
            <Badge
              variant={
                doc.status === 'Done'
                  ? 'done'
                  : doc.status === 'Ready'
                  ? 'accent'
                  : doc.status === 'Waiting'
                  ? 'waiting'
                  : 'neutral'
              }
              size="lg"
              dot
              pulse={doc.status === 'Waiting' || doc.status === 'Ready'}
            >
              {doc.status}
            </Badge>
          </div>
        </div>

        {/* Global Shortfall Warning Alert */}
        {linesWithShortfall.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: -6 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-4 rounded-xl bg-status-danger/15 border border-status-danger/40 text-red-300 flex items-start gap-3"
          >
            <AlertTriangle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
            <div>
              <div className="text-xs font-bold font-display uppercase tracking-wider text-red-200">
                Stock Allocation Shortfall Alert
              </div>
              <p className="text-xs text-red-300/90 mt-0.5">
                {linesWithShortfall.length} product line(s) have requested quantities exceeding available free inventory. Immediate replenishment or transfer required before dispatch.
              </p>
            </div>
          </motion.div>
        )}

        {/* Form Fields Header */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          <Input
            label={isReceipt ? 'Receive From (Vendor)' : 'Contact (Customer)'}
            value={isReceipt ? doc.partner : doc.contact}
            onChange={(e) =>
              setDoc({
                ...doc,
                [isReceipt ? 'partner' : 'contact']: e.target.value,
              })
            }
            leftIcon={<Building className="w-4 h-4" />}
            disabled={doc.status === 'Done'}
            required
          />

          {!isReceipt && (
            <Input
              label="Delivery Address"
              value={doc.deliveryAddress}
              onChange={(e) => setDoc({ ...doc, deliveryAddress: e.target.value })}
              leftIcon={<MapPin className="w-4 h-4" />}
              disabled={doc.status === 'Done'}
              required
            />
          )}

          <Input
            label="Responsible Operator"
            value={doc.responsible || 'Alex Vance'}
            readOnly
            leftIcon={<User className="w-4 h-4" />}
            helperText="Auto-filled to authenticated session"
          />

          <Input
            label={isReceipt ? 'Receipt Date' : 'Schedule Date'}
            type="date"
            value={doc.scheduleDate || doc.date || ''}
            onChange={(e) =>
              setDoc({
                ...doc,
                scheduleDate: e.target.value,
                date: e.target.value,
              })
            }
            leftIcon={<Calendar className="w-4 h-4" />}
            disabled={doc.status === 'Done'}
          />

          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-neutral-300 font-display uppercase tracking-wider">
              Warehouse Facility
            </label>
            <select
              value={doc.warehouse}
              onChange={(e) => setDoc({ ...doc, warehouse: e.target.value })}
              disabled={doc.status === 'Done'}
              className="w-full h-10 px-3.5 rounded-xl bg-canvas-subtle border border-white/[0.08] text-white focus:border-accent text-sm font-medium outline-none"
            >
              {INITIAL_WAREHOUSES.map((w) => (
                <option key={w.id} value={w.shortCode}>
                  [{w.shortCode}] {w.name}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* 4. PRODUCT LINES TABLE */}
        <div className="space-y-4 pt-4 border-t border-white/[0.08]">
          <div className="flex items-center justify-between">
            <h3 className="font-display font-bold text-base text-white uppercase tracking-wider">
              Product Operations Lines ({doc.lines.length})
            </h3>

            {doc.status !== 'Done' && !isAddingLine && (
              <Button
                variant="secondary"
                size="sm"
                leftIcon={<Plus className="w-3.5 h-3.5" />}
                onClick={() => setIsAddingLine(true)}
              >
                Add New Product
              </Button>
            )}
          </div>

          {/* Inline Add Product Line Form */}
          {isAddingLine && (
            <form
              onSubmit={handleAddProductLine}
              className="p-4 rounded-xl bg-surface-elevated/90 border border-accent/40 space-y-3 animate-in fade-in duration-150"
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold font-display text-white uppercase tracking-wider">
                  Add Item Line
                </span>
                <button
                  type="button"
                  onClick={() => setIsAddingLine(false)}
                  className="text-neutral-400 hover:text-white text-xs"
                >
                  Cancel
                </button>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="sm:col-span-2 space-y-1.5">
                  <label className="text-[11px] font-mono text-neutral-400 uppercase">
                    Select Product
                  </label>
                  <select
                    value={selectedProductId}
                    onChange={(e) => setSelectedProductId(e.target.value)}
                    className="w-full h-9 px-3 rounded-xl bg-canvas-subtle border border-white/[0.08] text-white text-xs font-medium outline-none"
                  >
                    {INITIAL_PRODUCTS.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.name} [{p.sku}] — Free: {p.freeToUse} {p.uom}
                      </option>
                    ))}
                  </select>
                </div>

                <Input
                  label="Quantity"
                  type="number"
                  min="1"
                  value={newLineQty}
                  onChange={(e) => setNewLineQty(e.target.value)}
                  required
                />
              </div>

              <div className="flex justify-end gap-2 pt-1">
                <Button
                  type="button"
                  variant="ghost"
                  size="xs"
                  onClick={() => setIsAddingLine(false)}
                >
                  Cancel
                </Button>
                <Button type="submit" variant="primary" size="xs">
                  Append Line
                </Button>
              </div>
            </form>
          )}

          {/* Product Lines Table */}
          <div className="rounded-xl border border-white/[0.08] overflow-hidden bg-canvas-subtle/50">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Product / Description</TableHead>
                  <TableHead>SKU</TableHead>
                  <TableHead className="text-right">
                    {isReceipt ? 'Expected Qty' : 'Demand Qty'}
                  </TableHead>
                  {!isReceipt && (
                    <TableHead className="text-right">Free in Stock</TableHead>
                  )}
                  {isReceipt && (
                    <TableHead className="text-right">Received Qty</TableHead>
                  )}
                  <TableHead>UoM</TableHead>
                  <TableHead>Status Check</TableHead>
                  {doc.status !== 'Done' && (
                    <TableHead className="text-right">Remove</TableHead>
                  )}
                </TableRow>
              </TableHeader>
              <TableBody>
                {doc.lines.length === 0 ? (
                  <TableRow>
                    <TableCell
                      colSpan={7}
                      className="text-center py-8 text-neutral-500 text-xs"
                    >
                      No product lines added yet. Click "Add New Product" above.
                    </TableCell>
                  </TableRow>
                ) : (
                  doc.lines.map((line) => {
                    const reqQty = line.expectedQty || line.qty;
                    const isShortfall = !isReceipt && line.availableQty < reqQty;

                    return (
                      <TableRow
                        key={line.id}
                        className={
                          isShortfall
                            ? 'bg-status-danger/10 border-b border-status-danger/30 text-red-200'
                            : ''
                        }
                      >
                        <TableCell>
                          <div className="font-semibold text-white">{line.name}</div>
                          {isShortfall && (
                            <div className="text-[11px] font-mono text-red-400 flex items-center gap-1 mt-0.5">
                              <AlertTriangle className="w-3 h-3" />
                              Insufficient stock (Available: {line.availableQty})
                            </div>
                          )}
                        </TableCell>

                        <TableCell mono className="font-semibold text-accent">
                          {line.sku}
                        </TableCell>

                        <TableCell mono className="text-right font-bold text-white">
                          {reqQty.toLocaleString()}
                        </TableCell>

                        {!isReceipt && (
                          <TableCell
                            mono
                            className={`text-right font-bold ${
                              isShortfall ? 'text-red-400' : 'text-emerald-400'
                            }`}
                          >
                            {(line.availableQty ?? 0).toLocaleString()}
                          </TableCell>
                        )}

                        {isReceipt && (
                          <TableCell mono className="text-right text-emerald-400">
                            {(line.doneQty || 0).toLocaleString()}
                          </TableCell>
                        )}

                        <TableCell className="text-xs text-neutral-400">
                          {line.uom}
                        </TableCell>

                        <TableCell>
                          {isShortfall ? (
                            <Badge variant="late" size="sm" dot pulse>
                              Shortfall Alert
                            </Badge>
                          ) : (
                            <Badge variant="done" size="sm">
                              Stock OK
                            </Badge>
                          )}
                        </TableCell>

                        {doc.status !== 'Done' && (
                          <TableCell className="text-right">
                            <button
                              type="button"
                              onClick={() => handleRemoveLine(line.id)}
                              className="p-1 rounded text-neutral-400 hover:text-red-400 transition-colors"
                              title="Delete row"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </TableCell>
                        )}
                      </TableRow>
                    );
                  })
                )}
              </TableBody>
            </Table>
          </div>
        </div>
      </Card>
    </div>
  );
}
